### ISSUE TITLE
What methods does Column have?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#107]
Currently, nothing is defined

https://github.com/data-apis/dataframe-api/blob/9673b3584438e5e059f5fe84bf3b6d14a3c5d8ef/spec/API_specification/dataframe_api/column_object.py#L1-L2

Just for my understanding, is this because it hasn't been done yet, or because it would be the same as from the Protocol?

https://github.com/data-apis/dataframe-api/blob/main/protocol/dataframe_protocol.py

**Comment by honno** [comment]
> Just for my understanding, is this because it hasn't been done yet, or because it would be the same as from the Protocol?
> 
> https://github.com/data-apis/dataframe-api/blob/main/protocol/dataframe_protocol.py

Hasn't been done yet. Its worth noting the df interchange protocol specifies columns used in interchange (say `df.__dataframe__().get_column(...)`), so doesn't have to be supported by a libraries "top-level" column object (i.e. `pd.Series`).

**Comment by rgommers** [comment]
> Hasn't been done yet.

Not quite. From gh-50, which is quite relevant here: _We had (/have) a pretty strong consensus that there should not be a separate Series-like object, but only a DataFrame object with a single column. IIRC the key issue is that Series and DataFrame have so much API duplication, for little benefit._ And that statement goes all the way back to gh-6, which contains a lot of the early discussion. The duplication pandas & co have with essentially duplicate APIs on the dataframe and series objects seemed undesirable to most folks.

That said, when actually implementing the interchange protocol we figured out that it's not 100% practical to not have a `Column` object at all. So the remaining question is what needs adding to a `Column` for an API, and where a single-column dataframe will do just fine.

**Comment by jorisvandenbossche** [comment]
While those older github issues indeed discussed to not have a separate 1D / column object, I seem to remember that on one of the more recent meetings where we discussed this, we landed on the opposite conclusion?

**Comment by jorisvandenbossche** [comment]
See https://github.com/data-apis/workgroup/blob/873d37ae66b1984fb3085cc1d5fe8634f3152aee/meeting_minutes/workgroup_meeting_2022_09_29.md?plain=1#L159-L277

**Comment by MarcoGorelli** [comment]
Is it enough to return a 1-column dataframe?

Say someone has the following (very common) pattern in pandas:
```python
In [33]: df = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]})

In [34]: mask = df['a'] > 1

In [35]: df.loc[mask, ]
Out[35]:
   a  b
1  2  5
2  3  6
```

How could this be written with the standard? If `Column` supported `__gt__`, say, then the following would work:

```python
df_standard = dataframe_standard(df)
mask = df.get_column_by_name('a') > 1
df_standard.get_rows_by_mask(mask)
```

Without a `Column`, or without `Column.__gt__`, what would the alternative be?

**Comment by rgommers** [comment]
> While those older github issues indeed discussed to not have a separate 1D / column object, I seem to remember that on one of the more recent meetings where we discussed this, we landed on the opposite conclusion?

Right, indeed - thank you for finding that discussion. I think we need to update gh-50 with a clear summary of that. The tl;dr would be _"so column is array-like and then has special behavior for missing values in reductions (with uniform `skip_na` kwarg across all functions), etc."_

**Comment by rgommers** [comment]
> I think we need to update [gh-50](https://github.com/data-apis/dataframe-api/issues/50) with a clear summary of that.

This is done now.

I believe this particular is resolved, since we have a good collection of methods on `Column`. So I'll close this issue.
