### ISSUE TITLE
Why does `set_column` exist?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#116]
I find this method a bit odd for two reasons.

First, it does two things: either replaces a column, or inserts a new one. This seems at odds with the rest of the Standard, which is typically quite strict and minimal.

Second, it can be implemented in terms of other Standard methods in just a few lines of code:
```python
    def set_column(self, label: str, value: Column) -> DataFrame:
        columns = self.get_column_names()
        if label in columns:
            idx = columns.index(label)
            return self.drop_column(label).insert(idx, label, value)
        return self.insert(len(columns), label, value)
```
Is this right?

If so, I'd suggest dropping it. Otherwise, if we're going to keep it just because it's convenient, then I'd argue that we should also have `value_counts`

**Comment by rgommers** [comment]
That implementation seems right - and yes, that does look like a convenience method. It seems not completely obvious though - 7 lines of code and something that's likely used somewhat frequently? (related, I did notice that `insert` is a bit of an outlier, for consistency with related methods I'd have guessed `insert_column`)

The case for `value_counts` is also convenience, right? Is it
```python
def value_counts(self, keys: Sequence[str], /, *,  skipna: bool = True) -> DataFrame:
    return self.groupby(keys).size(skipna=skipna)
```
or is there more to it?

**Comment by MarcoGorelli** [comment]
I'll add it to the next call's agenda - I'd advocate for removing it from the standard, and only putting it back if/when we find a use case
