### ISSUE TITLE
DataFrame.collect() for lazy dataframes?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#120]
Some DataFrames have a lazy api, which the standard should probably support

Should we add a `collect` method, which for eager libraries would just return `self` and for lazy ones would materialise the dataframe?

**Comment by rgommers** [comment]
I think the answer here is that the API is fully compatible with implementations that use lazy evaluation, and that it should not have specific syntax. We should probably document that

**Support for lazy evaluation**

We have to design all APIs to support lazy evaluation, and I think so far there's nothing in the draft API that's incompatible with that. It's basically the same as in the array API, quoting from [here](https://data-apis.org/array-api/draft/assumptions.html): _The same applies to software environments: it must be possible to create an array library adhering to this standard that runs efficiently independent of what compilers, build-time or run-time execution environment, or distribution and install method is employed. Parallel execution, JIT compilation, and delayed (lazy) evaluation must all be possible._

As a design rule, the syntax and semantics of the API must be independent of execution model. Which by definition rules out something like `.collect()`. Execution of code written in the API backed by a lazy implementation can probably be triggered by (a) library-specific implementation details where the implementation must graph break for some reasons (full Python branching like on if-else not supported for example), (b) interop with another library, like when `__dataframe__` is called, and (c) the user explicitly asking for an execution step with `.collect()` or similar.

**Syntax variations between libraries for lazy execution**

This is very non-uniform and would be hard to standardize anyway. E.g.:
- Dask is always lazy and has a `.compute()` method to trigger execution
- Vaex offers both eager and lazy execution (see [here](https://vaex.io/docs/guides/async.html#Using-delay=True)), uses `.execute()` to trigger and `delay=True` or `@delayed` to choose the lazy mode over the eager one
- Polars also offers both eager and lazy (see [here](https://pola-rs.github.io/polars-book/user-guide/lazy-api/lazy-query-execution.html)), and uses `.collect()` to trigger execution and `.lazy()` or lazy-specific I/O functions like `pl.scan_csv` to choose lazy mode.

**How this should work**

```python
import a_dataframe_lib

# Create a dataframe and lazy mode, may be library-specific I/O or apply explicit syntax like @delayed
df = a_dataframe_lib.xxx
# Use standard API
....
df_out = ...

# Now we have, for example, `df_out` as the result of use of standard-compliant API
# This can now be materialized by something like:
df_out.compute()  # Dask-specific
```

**Comment by rgommers** [comment]
> then perhaps the call to `.collect` can be taken care of inside `to_array` and can be seen as an implementation detail

That sounds about right to me.

**Comment by kkraus14** [comment]
Agreed, depending on the semantics of the `to_array` call and what guarantees it provides, if materialized data is required then the framework implementing the API would be responsible for handling that in its `to_array` implementation.

**Comment by MarcoGorelli** [comment]
thanks all, closing then

**Comment by MarcoGorelli** [comment]
re-opening as scikit-learn have mentioned that they would like to collect separately from converting to ndarray

**Comment by MarcoGorelli** [comment]
Thanks, let's discuss tomorrow. I'm realising that there's far, far more to the topic of lazy dataframes, I'll add it to the agenda

**Comment by MarcoGorelli** [comment]
closing as this discussion has effectively moved to https://github.com/data-apis/dataframe-api/issues/224

**Comment by MarcoGorelli** [comment]
Revisiting this, I think it's sufficiently different from #224 that it needs to stay open

> then perhaps the call to .collect can be taken care of inside to_array and can be seen as an implementation detail

I no longer stand by this, this would potentially result in double-computation, e.g.:
```python
mask = df.get_column_by_name('flag') == 'train'
x_train = df.get_rows_by_mask(mask)
x_test = df.get_rows_by_mask(~mask)
my_fancy_algorithm.fit(x_train.to_array_object(), x_test.to_array_object())
```

In fact, Dask devs have told me that their users sometimes accidentally trigger compute twice, because some of their methods do that under-the-hood for them.

I'm against anything other than an explicit `.collect` (or `compute`) triggering computation. If `collect` can't make its way into the standard, then OK, so be it, lazy computations will stay lazy and eager computations will stay eager
