### ISSUE TITLE
Column constructor

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#121]
For constructing DataFrames, we have `DataFrame.from_dict`

How about constructing a Column? Example of where this would be needed:

https://github.com/mwaskom/seaborn/blob/5d9f37159bbd3ac44c8c8a06825583ba25648525/seaborn/_oldcore.py#L1217-L1220

```python
        for var in axis_variables:
            other_var = {"x": "y", "y": "x"}[var]

            converter = pd.Series(index=self.plot_data.index, name=var, dtype=object)
```

**Comment by rgommers** [comment]
Seems like we need this. One comment during today's call was that these kind of constructors are quite messy in existing libraries, mainly for two reasons: they take a large number of types of input (arrays, scalars, sequences, generators, etc.) as well as do dtype inference on the contents. It looks like we want to avoid that, by only accepting well-defined input types (probably sequence and array?) and having the caller specify the dtype. Each element of input sequences must be of that dtype.
