### ISSUE TITLE
GroupBy.size

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#122]
Using GroupBy.size was suggested as an alternative to having `value_counts`, but it still needs adding

**Comment by MarcoGorelli** [comment]
I'd have thought this one should also have `skipna` if the other `groupby` methods do?

**Comment by rgommers** [comment]
Yes indeed - I think I had that in another comment, but forgot it here.

**Comment by jorisvandenbossche** [comment]
Presence of missing values is something that can be determined per column, while the size if about the full group (not a specific column in that group). So I am not sure adding `skipna` makes sense here (or, what behaviour would it exactly have?)

Also in pandas the GroupBy.size method doesn't have this keyword.

**Comment by MarcoGorelli** [comment]
ah right, I thought there was probably a reason why pandas didn't have this keyword

cool, leaving it out then
