### ISSUE TITLE
DataFrame.sort(by=labels: Sequence[str])

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#123]
There's currently no sorting functionality. OK to add `DataFrame.sort` which takes a sequence of column names to sort by?

**Comment by kkraus14** [comment]
+1 from me

**Comment by jorisvandenbossche** [comment]
I think people will want to be able to specify if it is an ascending or descending sort?

In addition to a general ascending/descending flag, some other possible options that I am aware off in other systems: ability to specify ascending/descending per sort key, specify behaviour of sorting NaNs/nulls (first vs last)

**Comment by MarcoGorelli** [comment]
good point, thanks! have added both
