### ISSUE TITLE
Why does GroupBy.sum have skipna, and what would it mean?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#132]
First, looking at existing DataFrame libraries:
- pandas doesn't have it: https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.sum.html
- polars doesn't have it: https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.dataframe.groupby.GroupBy.sum.html#polars.dataframe.groupby.GroupBy.sum
- cudf: I don't know, what values are accepted as `args` and `kwargs`? https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.core.groupby.groupby.groupby.sum

Second what does skipna mean? Care has been taken to separate `is_null` (missing values) from `isnan` (nan-like, e.g. resulting from 0/0), but which one does `skipna` in `GroupBy.sum` refer to, and what's the expected result if `skipna=False`? And what's the use-case?

**Comment by jorisvandenbossche** [comment]
I think that's just a limitation (missing feature) in the pandas API. But asking a question in return: what does the keyword do for a normal `sum`? (I think that is clearly defined: if you have any null, the result is null, i.e. propagating any missing values instead of skipping them) 
Both pandas and the standard have the keyword for the `DataFrame.sum()` method (and for column/series equivalent), how would a grouped version be any different?

**Comment by MarcoGorelli** [comment]
Is it skip_null or skip_nan though? Say you have `[1., nan, null]` - what's their sum both `skipna` True, and for when it's False?

**Comment by MarcoGorelli** [comment]
shall we rename it `skip_nan` then, for consistency with `isnan`?

**Comment by rgommers** [comment]
No, the intent is to skip nulls, not floating point `nan` values.

**Comment by rgommers** [comment]
Or did you mean `skip_null`? I don't know, we need to be consistent and use either `null` or `na` everywhere.

**Comment by MarcoGorelli** [comment]
yeah we need to be consistent, if the intent is to just skip nulls then let's call it `skip_nulls`

**Comment by rgommers** [comment]
There should also be a singleton, which we intended to call `NA`. And `dropna`. `describe_null` in the interchange protocol Perhaps more - will be good to either always use `null` or always `na`.

**Comment by rgommers** [comment]
gh-134 goes for the `null` name. Seems good to me. More distinct from `nan` than `na`, so less confusing. And easier because we can't change `describe_null` anymore.
