### ISSUE TITLE
Column.unique

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#135]
Any objections to adding `Column.unique` to get the unique values in a `Column`?
It could return another `Column` with just the unique values.

Why do we need this? From https://github.com/data-apis/dataframe-api/issues/131#issuecomment-1497364901, if we're disallowing iterating over groups, then the workaround is to find the unique values, filter by them, and apply the user-defined function each time

**Comment by rgommers** [comment]
adding a `unique` method to columns seems perfectly reasonable to me. I'm not even sure it needs that detailed a rationale - `unique` is a pretty fundamental operation for dataframe libraries I'd think, and hence having that as a method on both dataframes and columns seems expected.

**Comment by kkraus14** [comment]
+1 on the function

We may want to document any ordering guarantees or lack thereof as well.

**Comment by jorisvandenbossche** [comment]
> We may want to document any ordering guarantees or lack thereof as well.

Probably the lack of any ordering guarantee? So neither sorted (what numpy does) or order of appearance (what pandas does)?
