### ISSUE TITLE
Should groupby.size just return Column?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#143]
Currently it's annotated to return `DataFrame`, but I'd suggest it just return a single `Column`

Unlike other groupby methods, this one doesn't depend on how many columns there are, it just depends on the columns you're grouping by

**Comment by kkraus14** [comment]
We still need a way to map those sizes to their associated groups which would be via the other columns in the DataFrame?

**Comment by MarcoGorelli** [comment]
ah sorry, you're right, no index - closing then
