### ISSUE TITLE
Inserting a column of nans / namespace.column_class

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#162]
Motivation: in seaborn they insert a column of `'nan'`s at one point, which in pandas is as simple as
```python
df[new_column_name] = np.nan
```
How do we do that within the Standard? I'm currently doing something like:
```python
df: DataFrame
namespace = df.__dataframe_namespace__()
df= df.insert(
    df.shape()[1],
    new_column_name,
    namespace.column_class.from_sequence([float('nan')] * len(df)), dtype="float64"),
)
```
, is that OK?

If so, it would require adding a `namespace.column_class` method, which would do something like:
```python
>>> df: PandasDataFrame
>>> namespace = df.__dataframe_namespace__()
>>> namespace.column_class
PandasColumn
>>> df: PolarsDataFrame
>>> namespace = df.__dataframe_namespace__()
>>> namespace.column_class
PolarsColumn
>>> # etc...
```

**Comment by rgommers** [comment]
That looks a bit hard to understand. It suggests a change to `insert` may be useful, as well as a free function constructor, so it can be written as:
```python
ns = df.__dataframe_namespace__()
col_nans = ns.from_sequence([float('nan')] * df.shape()[0]), dtype="float64"),
df= df.insert('new_nancol', col_nans, loc=df.shape()[1])
``` 

This highlights my the uneasiness I felt with the `classmethod` constructors: it enforces knowing the exact name of the class. There is a reason why constructors are functions in array libraries, I think it's strictly superior. Adding a function to retrieve that class name instead can't be the right solution.

**Comment by MarcoGorelli** [comment]
`ns.from_sequence` looks good too, thanks!
