### ISSUE TITLE
testing functionality

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#168]
I think we need some testing functionality, as we'll need some test suite to check that all implementations pass it and raise errors when appropriate (e.g.` pd.DataFrame([[1, 2]]).__dataframe_standard__()` should raise)

Shall we add
- `namespace.assert_frame_equal`
- `namespace.assert_series_equal`
?

Signature could be
```
def assert_frame_equal(df1, df2, *, exact, atol, rtol)
```

Missing values: `'nan'` and null values should match?

Other than that, I'd force `dtype` and columns order to match, no need to add configuration for that

**Comment by rgommers** [comment]
Wouldn't it be better to keep that completely separate, a la https://github.com/data-apis/array-api-tests/?

**Comment by MarcoGorelli** [comment]
sure, not saying they need to be part of the standard, but I'm currently writing tests like
```python
def test_get_column_by_name() -> None:
    df = PandasDataFrame(pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]}))
    result = df.get_column_by_name("a")._series
    expected = pd.Series([1, 2, 3], name="a")
    pd.testing.assert_series_equal(expected, result)
```
which isn't ideal, some way of asserting equality between `Column`/`DataFrame` objects would really help

**Comment by MarcoGorelli** [comment]
taking this forwards in https://github.com/MarcoGorelli/impl-dataframe-api
