### ISSUE TITLE
"dataframe API" is too generic of a name

### ISSUE THREAD

**Issue by itamarst** [data-apis/dataframe-api#177]
A week or three ago somewhere on social media I saw a library scroll by saying they just released prototype support for the dataframe API.  Social media history being what it is, I can't find that anymore.

1. They possibly meant this one, but I can't be sure at this point.
2.  I have no way of finding that project, because googling for "Dataframe API" or variants is far too generic.

**Comment by rgommers** [comment]
@itamarst thanks for your question. There are two separate things:

1. The _dataframe interchange protocol_
2. The _dataframe API standard_

Both names seem searchable. Given that (2) isn't quite released yet, my guess is that the tweet was about (1) (I know VegaFusion and Altair added support for it not too long ago).

Does that address your question/concern?
