### ISSUE TITLE
Return type of groupby.size

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#180]
Should we standardise the return type here?

polars return uint32
```python
In [21]: pl.DataFrame({'a': [1,2,2]}).groupby('a').count()
Out[21]:
shape: (2, 2)
┌─────┬───────┐
│ a   ┆ count │
│ --- ┆ ---   │
│ i64 ┆ u32   │
╞═════╪═══════╡
│ 2   ┆ 2     │
│ 1   ┆ 1     │
└─────┴───────┘
```
whereas pandas 'int64'
```python
In [22]: pd.DataFrame({'a': [1,2,2]}).groupby('a').size().dtypes
Out[22]: dtype('int64')
```

**Comment by rgommers** [comment]
Is it possible to get an answer that doesn't fit in 32 bits from Polars, and if so how is that handled?

**Comment by MarcoGorelli** [comment]
just trying to run
```python
import polars as pl
df=pl.LazyFrame().with_columns(values=pl.arange(0,4_000_000_000, eager=False))

df.groupby('values').count().collect()
```
I get `killed`

but more than on the 32 vs 64, should we standardise on unsigned vs signed?

**Comment by rgommers** [comment]
> but more than on the 32 vs 64, should we standardise on unsigned vs signed?

That's probably a good idea. I'd expect signed integers to be more common and unsigned integers to be pretty rarely used for any dataframe method (as soon as you do arithmetic you may have to convert them to signed; it's not even clear to me that all dataframe libraries support all unsigned integer types). It'd be useful to check more libraries for what they currently do.
