### ISSUE TITLE
Python DataFrame Summit 2023

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#196]
Just sharing for visibility: https://df-summit-23.pydata.org/

Some members of some projects will be meeting just before EuroScipy 2023 to discuss DataFrames. No doubt Consortium topics will come up

If anyone's interested in attending but didn't know about it, please do get in contact

**Comment by rgommers** [comment]
Thanks for sharing @MarcoGorelli, and for organizing @datapythonista! Sounds like an interesting gathering.

It may be useful to keep this issue open to link to any write-ups/outcomes, unless there is a better place to follow along async?

**Comment by datapythonista** [comment]
This is the "production" url, I think there have been couple of attendee changes since the draft I published in the one you shared (I'll take it down to avoid confusion): https://df-summit-23.pydata.org/
