### ISSUE TITLE
Methods for casting from one dtype to another

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#203]
Should the standard support casting columns from one dtype to another? Like, Int64 -> Float64?

Could have:
- `DataFrame.cast_columns`, which takes a mapping between column names and dtypes
- `Column.cast` which accepts a single dtype

**Comment by adityagoel4512** [comment]
I also prefer `astype` for the name, although the proposal seems entirely sensible to me! And the less that is implicit the better here regarding the `null` handling in my opinion. `column.cast(namespace.Float64).to_array_object()` should, in your example, yield `[1., 2., null, 4.]`.

**Comment by MarcoGorelli** [comment]
> yield [1., 2., null, 4.]

sorry how would it yield `null` in an array library (which typically doesn't distinguish nan and null)? do you mean `[1., 2., nan, 4.]`?

**Comment by adityagoel4512** [comment]
You're right actually given the `to_array_object` at the end. I meant merely to not close the door for libraries to distinguish them if possible in the column casting (prominent example being polars Series where `null` and `nan` are distinguished).
