### ISSUE TITLE
Set first `api_version`

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#210]
Are we OK to:
- merge open non-draft PRs
- add a git tag `2023-07` (or `2023-08`)

?

Then I can start upstreaming `__dataframe_consortium_standard__` methods which defer to the `dataframe-api-compat` package (or at least, try to)

**Comment by MarcoGorelli** [comment]
as per today's discussion - once #223 is in, let's push a `2023-08-beta` tag

Is there anything else that needs doing here for releases?

**Comment by rgommers** [comment]
I can't think of other things. Please go ahead and push the tag @MarcoGorelli! You did most of the implementation work here, so I'd say you get to do the honours for tagging the first beta as well here:)
