### ISSUE TITLE
Perfect backwards compatibility

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#220]
Looks like we're close to tagging a first version

Do we want to aim for some guarantee of perfect backwards compatibility?

So, if you write your code using the `2023-08` version, then it should all still work under the `2025-01` version. The latter may have some extra features, or some extra optional arguments, but anything you write with the `2023-08` version should still work with the `2025-01` one

**Comment by MarcoGorelli** [comment]
Sure, we'll probably make mistakes and require breaking changes in the short-term

But longer-term, do we want to get to the point where it should all be perfectly backwards compatible (like Rust is between its editions)? I think it'd be pretty nice

**Comment by rgommers** [comment]
Yes, definitely! I think we want to give very strong guarantees here, any bc-breaking changes between stable versions should be exceptional. We have a small and carefully designed API surface, and it should be significantly more stable than that of any dataframe library out there. More a la a C/C++ language standard.

**Comment by MarcoGorelli** [comment]
addressed by https://github.com/data-apis/dataframe-api/issues/257
