### ISSUE TITLE
`insert` or `insert_column`?

### ISSUE THREAD

**Issue by ivirshup** [data-apis/dataframe-api#236]
Hey, I wanted to note some inconsistent naming of the `insert`/ `insert_column` method.

* This method is called [`insert_column`](https://data-apis.org/dataframe-api/draft/API_specification/dataframe_object.html#dataframe_api.DataFrame.insert_column) in the spec

<img width="1037" alt="image" src="https://github.com/data-apis/dataframe-api/assets/8238804/be1bf898-2212-4dc2-b2d2-e1fa9d73a630">

* But it's example uses a `insert` method
* In the API package, the method is [`insert`](https://github.com/data-apis/dataframe-api-compat/blob/fde3afdfb651f389fdee4b9e6d4eaaab1ebc09bf/dataframe_api_compat/pandas_standard/pandas_standard.py#L548)

**Comment by MarcoGorelli** [comment]
Thanks for the report! will fix

**Comment by MarcoGorelli** [comment]
this was just renamed today, the correct one is `insert_column`

the api version is still "beta" so there may be changes, but the plan is to try to have an extremely stable API once the design is sorted out

**Comment by MarcoGorelli** [comment]
there's now `assign`, which covers both inserting and updating - closing then
