### ISSUE TITLE
Dealing with `if scalar`

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#315]
The whole discussion around `to_array` is quite tricky, see https://github.com/data-apis/dataframe-api/pull/294 and https://github.com/data-apis/dataframe-api/pull/307 . One big difficulty is that for some libraries it can stay lazy (e.g. Dask has a lazy array), whereas for others it can't (polars LazyFrame doesn't have a `to_numpy` attribute)

Maybe we can temporarily park it, and try to address the more important (arguably) issue of what to do about
```python
df: DataFrame
features = []
for column_name in df.column_names:
    if df.col(column_name).std() > 0:
        features.append(column_name)
return features
```

Because as far as I can tell, this call is problematic for all libraries other than purely eager ones. Even Dask, which was mentioned in #294 as an example of a library which can stay lazy in `to_array`, raises in the call above (see [here](https://github.com/data-apis/dataframe-api/pull/307/files#diff-8431d340ff0d5bce38d6d83ad94460668ab4cafbb8a2c77527798e885723f7a3)).

Dask raises here, it doesn't do any implicit computation.

So...what do we do here? Maybe let's try resolving this one, and then return to `to_array`?

I'll hold off making suggestions this time, let's let the discussion roll

**Comment by cbourjau** [comment]
This seems related to #305 and what ought to happen if `__bool__` is called on a `Scalar`. Any solution should probably incorporate the lessons learned from the analogous [discussion](https://github.com/data-apis/array-api/issues/642) for the array-api. In #305 I try to [argue](https://github.com/data-apis/dataframe-api/issues/305#issuecomment-1795927924) for piggy-backing on the array-API which would move this problem out of the scope of the dataframe API 🪄 .

**Comment by MarcoGorelli** [comment]
I think we've resolved this now - `__bool__` forces computation or raises (implementation-dependent), and it may be necessary to call `persist` first (also implementation-dependent)
