### ISSUE TITLE
How will cudf handle `df.assign(df.col('a').sort())`?

### ISSUE THREAD

**Issue by MarcoGorelli** [data-apis/dataframe-api#344]
It's been brought up that cudf won't implement a separate namespace with the standard, but rather that their main namespace will be compliant

Just for my understanding, what do you intend to do about `df.assign(df.col('a').sort())`?

pandas behaviour: do nothing, because it aligns on the index
```python

In [4]: df
Out[4]:
   a
0  4
1  1
2  2

In [5]: df.assign(b=lambda x: x['a'].sort_values())
Out[5]:
   a  b
0  4  4
1  1  1
2  2  2
```

Standard behaviour: insert the sorted values:
```python
In [1]: df = pd.DataFrame({'a': [4, 1, 2]})

In [2]: dfs = df.__dataframe_consortium_standard__()

In [3]: dfs.assign(dfs.col('a').sort().rename('b')).dataframe
Out[3]:
   a  b
0  4  1
1  1  2
2  2  4
```

@shwina @kkraus14

**Comment by MarcoGorelli** [comment]
@shwina @kkraus14 gentle ping, this is quite important

**Comment by shwina** [comment]
Apologies for missing this Marco. Yeah great observation: I expect that recent additions to the standard such as lazy semantics and column expressions are going to need cuDF also to have a separate namespace to support the standard.

**Comment by MarcoGorelli** [comment]
We don't have column expressions in the Standard

But now that you bring it up...let's try this again https://github.com/data-apis/dataframe-api/issues/346

**Comment by kkraus14** [comment]
Since we disallowed operations across columns from different dataframes and I imagine the sorting operation would invalidate the parent dataframe, wouldn't doing something like:
```
dfs.col('a') + (dfs.col('a').sort())
```
be disallowed? If that's the case why would we allow assigning it to a DataFrame without using a join explicitly?

**Comment by MarcoGorelli** [comment]
> I imagine the sorting operation would invalidate the parent dataframe

Incorrect. It's only the column that's being sorted, not the whole dataframe. `dfs.col('a')` and `dfs.col('a').sort()` have the same parent dataframe.

**Comment by kkraus14** [comment]
But logically wouldn't we be adding a column with a defined order to a dataframe with arbitrary / undefined order and we disallowed cross dataframe column operations to avoid this specific situation?

There's no way to express this in SQL without a join on a row number for example.

Trying to do this in Ibis errors with the DuckDB backend and the PySpark backend, returns incorrect results with the Pandas backend, and works with the Polars backend:

```
import ibis
from ibis import _

con = ibis.${BACKEND}.connect()  #duckdb, pyspark, pandas, polars, etc.
con.create_table("table", ibis.memtable({"a": [1, 2, 3], "b": [4, 5, 6]})
table = con.table("table")

table.mutate(c = _.a.desc()).execute()
```

Trying to do this with PySpark's DataFrame API directly errors that it can't generate code for the expression:
```
from pyspark.sql import Row, SparkSession

spark = SparkSession.builder.getOrCreate()
table = spark.createDataFrame([
    Row(a = 1, b = 4),
    Row(a = 2, b = 5),
    Row(a = 3, b = 6)
])

table.withColumn("c", table["a"].desc()).collect()
```

It seems like only Polars supports this in the way you're describing?

**Comment by MarcoGorelli** [comment]
Could you please give an example of `Column.sort` which you think should be supported

**Comment by MarcoGorelli** [comment]
Anyway, the amount of confusion here underscores just how complicated, difficult to teach, and unusable the current API is

Rather than trying to shoehorn about 4 different concepts into just two classes, there is a simpler way forwards: https://github.com/data-apis/dataframe-api/issues/346

Then, instead of all these "parent dataframe" complications, we can just say "index alignment is unsupported - join dataframes before hand".

**Comment by MarcoGorelli** [comment]
Going back to https://github.com/data-apis/dataframe-api/issues/347#issuecomment-1910737323 - if you know that `df` has a defined order, then `df.assign(df.col('a').sort().rename('b'))` is well-defined, right?

**Comment by kkraus14** [comment]
> Going back to [#347 (comment)](https://github.com/data-apis/dataframe-api/issues/347#issuecomment-1910737323) - if you know that `df` has a defined order, then `df.assign(df.col('a').sort().rename('b'))` is well-defined, right?

I would argue it is, yes. But so is using any other arbitrary column that doesn't necessarily need to originate from `df` that has a defined order.
